### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by lubnaabd** [FACG5/gsgca-project#24]
> create database
 
- [x] db_build.js
 - [x] db_build.sql
 - [x] db_connection.js

 ### Database Schema
 ![DB_SCHEMA](https://files.gitter.im/ela-team/ela-team/YNZF/Screenshot-from-2018-09-13-14-11-09.png)

**Comment by NouraldinS** [comment]
@lubnaabd What is the schema of your database? Draw it on https://www.dbdesigner.net/designer and upload a pic of it here.
